import { supabase } from '../lib/supabaseClient'

// Maps a Supabase row graph (products + product_categories + variants +
// images) into the exact flat shape every existing frontend consumer
// already expects (ProductCard, ProductDetail, cartPricing, reports,
// AdminProducts, ProductForm, ...) — this mapping is what lets every
// one of those files keep working completely unchanged.
function mapProductRow(row) {
  const images = [...(row.product_images ?? [])].sort((a, b) => a.sort_order - b.sort_order)
  const primaryImage = images.find((image) => image.is_primary) ?? images[0]

  return {
    id: row.id,
    name: row.name,
    slug: row.slug,
    category: row.product_categories?.name ?? '',
    description: row.description,
    shortDescription: row.short_description,
    image: primaryImage?.image_url ?? '',
    isActive: row.is_active,
    variants: (row.product_variants ?? [])
      .map((variant) => ({
        id: variant.id,
        name: variant.name,
        quantityValue: variant.quantity_value,
        unit: variant.unit,
        price: Number(variant.price),
        stock: variant.stock_quantity,
        isActive: variant.is_active,
        minOrderQty: variant.min_order_qty,
        maxOrderQty: variant.max_order_qty,
      }))
      .sort((a, b) => a.name.localeCompare(b.name)),
  }
}

const PRODUCT_SELECT = `
  id, name, slug, description, short_description, is_active, category_id,
  product_categories ( name ),
  product_variants ( id, name, quantity_value, unit, price, stock_quantity, is_active, min_order_qty, max_order_qty ),
  product_images ( id, image_url, alt_text, sort_order, is_primary )
`

// Deliberately ONE query, no "give me active only" flag — RLS itself
// decides what a given session can see (customers/anon only ever get
// active rows back; an authenticated admin session also gets inactive
// ones), so this single function is correct for every caller.
export async function fetchProducts() {
  const { data, error } = await supabase.from('products').select(PRODUCT_SELECT)
  if (error) throw error
  return (data ?? []).map(mapProductRow)
}

export async function fetchCategories() {
  const { data, error } = await supabase.from('product_categories').select('id, name').order('name')
  if (error) throw error
  return data ?? []
}

async function getCategoryId(categoryName) {
  const { data, error } = await supabase
    .from('product_categories')
    .select('id')
    .eq('name', categoryName)
    .maybeSingle()
  if (error) throw error
  if (!data) throw new Error(`Unknown category: ${categoryName}`)
  return data.id
}

// Replaces every variant row for a product with exactly the submitted
// list — upserting ones that still exist, inserting new ones, and
// deleting any existing variant that's no longer in the list (mirrors
// ProductForm.jsx's "Remove" button, which already works this way
// against the old localStorage array).
async function syncVariants(productId, variants) {
  const { data: existing, error: fetchError } = await supabase
    .from('product_variants')
    .select('id')
    .eq('product_id', productId)
  if (fetchError) throw fetchError

  const submittedIds = new Set(variants.filter((v) => v.id && !v.id.startsWith('variant-')).map((v) => v.id))
  const toDelete = (existing ?? []).filter((row) => !submittedIds.has(row.id)).map((row) => row.id)

  if (toDelete.length > 0) {
    const { error: deleteError } = await supabase.from('product_variants').delete().in('id', toDelete)
    if (deleteError) throw deleteError
  }

  for (const variant of variants) {
    const payload = {
      product_id: productId,
      name: variant.name,
      quantity_value: variant.quantityValue,
      unit: variant.unit,
      price: variant.price,
      stock_quantity: variant.stock,
      is_active: variant.isActive,
      min_order_qty: variant.minOrderQty || 1,
      max_order_qty: variant.maxOrderQty || null,
    }

    const isNew = !variant.id || variant.id.startsWith('variant-')
    const { error: upsertError } = isNew
      ? await supabase.from('product_variants').insert(payload)
      : await supabase.from('product_variants').update(payload).eq('id', variant.id)

    if (upsertError) throw upsertError
  }
}

export async function createProduct(productData) {
  const categoryId = await getCategoryId(productData.category)
  const slug = productData.name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')

  // `id` is generated by ProductForm.jsx (crypto.randomUUID()) BEFORE
  // the row exists, so an image can be uploaded to Storage under
  // products/{id}/... while the admin is still filling out the form.
  // The column still defaults to gen_random_uuid() for any other
  // caller that doesn't supply one.
  const { data: product, error } = await supabase
    .from('products')
    .insert({
      ...(productData.id ? { id: productData.id } : {}),
      category_id: categoryId,
      name: productData.name,
      slug,
      description: productData.description,
      short_description: productData.shortDescription,
      is_active: productData.isActive,
    })
    .select('id')
    .single()
  if (error) throw error

  await syncVariants(product.id, productData.variants)

  if (productData.image) {
    const { error: imageError } = await supabase
      .from('product_images')
      .insert({ product_id: product.id, image_url: productData.image, sort_order: 0, is_primary: true })
    if (imageError) throw imageError
  }

  return product.id
}

export async function updateProduct(productId, productData) {
  const categoryId = await getCategoryId(productData.category)

  const { error } = await supabase
    .from('products')
    .update({
      category_id: categoryId,
      name: productData.name,
      description: productData.description,
      short_description: productData.shortDescription,
      is_active: productData.isActive,
      updated_at: new Date().toISOString(),
    })
    .eq('id', productId)
  if (error) throw error

  await syncVariants(productId, productData.variants)

  if (productData.image) {
    const { error: imageError } = await supabase
      .from('product_images')
      .upsert(
        { product_id: productId, image_url: productData.image, sort_order: 0, is_primary: true },
        { onConflict: 'product_id,sort_order' }
      )
    if (imageError) throw imageError
  }
}

export async function setProductActive(productId, isActive) {
  const { error } = await supabase
    .from('products')
    .update({ is_active: isActive, updated_at: new Date().toISOString() })
    .eq('id', productId)
  if (error) throw error
}

// Uploads a new primary image for a product to Supabase Storage and
// points product_images at the resulting public URL. `productId` must
// already exist (the caller generates/has the id before calling this).
export async function uploadProductImage(productId, file) {
  const path = `products/${productId}/${Date.now()}-${file.name}`
  const { error: uploadError } = await supabase.storage
    .from('product-images')
    .upload(path, file, { upsert: true })
  if (uploadError) throw uploadError

  const { data } = supabase.storage.from('product-images').getPublicUrl(path)
  return data.publicUrl
}
